if (TARGET SweetEditor3p::Simdutf)
    return()
endif ()

set(SWEETEDITOR_3P_SIMDUTF_LIBRARY)

if (ANDROID)
    set(SWEETEDITOR_3P_SIMDUTF_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/lib/android/${CMAKE_ANDROID_ARCH_ABI}/release/libsimdutf.a)
elseif (OHOS)
    set(SWEETEDITOR_3P_SIMDUTF_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/lib/ohos/${OHOS_ARCH}/release/libsimdutf.a)
elseif (WIN32)
    if (MSVC)
        if (CMAKE_BUILD_TYPE STREQUAL "Release")
            set(SWEETEDITOR_3P_SIMDUTF_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/lib/windows/x64/release/simdutf.lib)
        else ()
            set(SWEETEDITOR_3P_SIMDUTF_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/lib/windows/x64/debug/simdutf.lib)
        endif ()
    else ()
        set(SWEETEDITOR_3P_SIMDUTF_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/lib/windows/x64/release/libsimdutf.a)
    endif ()
elseif (APPLE)
    if (CMAKE_SYSTEM_NAME STREQUAL "iOS")
        if (CMAKE_OSX_SYSROOT MATCHES ".*[Ss]imulator.*" OR CMAKE_OSX_SYSROOT STREQUAL "iphonesimulator")
            set(SWEETEDITOR_3P_SIMDUTF_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/lib/ios/simulator-${CMAKE_OSX_ARCHITECTURES}/release/libsimdutf.a)
        else ()
            set(SWEETEDITOR_3P_SIMDUTF_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/lib/ios/${CMAKE_OSX_ARCHITECTURES}/release/libsimdutf.a)
        endif ()
    else ()
        set(_SWEETEDITOR_3P_MACOS_ARCH ${CMAKE_OSX_ARCHITECTURES})
        if (NOT _SWEETEDITOR_3P_MACOS_ARCH OR _SWEETEDITOR_3P_MACOS_ARCH STREQUAL "")
            execute_process(COMMAND uname -m OUTPUT_VARIABLE _SWEETEDITOR_3P_MACOS_ARCH OUTPUT_STRIP_TRAILING_WHITESPACE)
        endif ()
        set(SWEETEDITOR_3P_SIMDUTF_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/lib/macos/${_SWEETEDITOR_3P_MACOS_ARCH}/release/libsimdutf.a)
    endif ()
elseif (EMSCRIPTEN)
    set(SWEETEDITOR_3P_SIMDUTF_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/lib/emscripten/release/libsimdutf.a)
elseif (UNIX AND NOT APPLE)
    if (CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64)$")
        set(SWEETEDITOR_3P_SIMDUTF_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/lib/linux/aarch64/release/libsimdutf.a)
    elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64)$")
        set(SWEETEDITOR_3P_SIMDUTF_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/lib/linux/x86_64/release/libsimdutf.a)
    else ()
        message(FATAL_ERROR "Unsupported Linux processor for prebuilt simdutf: ${CMAKE_SYSTEM_PROCESSOR}")
    endif ()
endif ()

if (NOT SWEETEDITOR_3P_SIMDUTF_LIBRARY OR NOT EXISTS ${SWEETEDITOR_3P_SIMDUTF_LIBRARY})
    message(FATAL_ERROR "Unsupported or missing simdutf prebuilt library: ${SWEETEDITOR_3P_SIMDUTF_LIBRARY}")
endif ()

message(STATUS "Add third-party library: ${SWEETEDITOR_3P_SIMDUTF_LIBRARY}")
add_library(sweeteditor_3p_simdutf STATIC IMPORTED)
set_target_properties(sweeteditor_3p_simdutf PROPERTIES IMPORTED_LOCATION ${SWEETEDITOR_3P_SIMDUTF_LIBRARY})

target_include_directories(sweeteditor_3p_simdutf
        INTERFACE
        ${CMAKE_CURRENT_LIST_DIR}/include
        ${CMAKE_CURRENT_LIST_DIR}/include/simdutf
)

add_library(SweetEditor3p::Simdutf ALIAS sweeteditor_3p_simdutf)
