// GENERATED by tools/kotlin_protocol_gen/generate.py. Do not edit.
package io.github.lumkit.sweeteditor.core.protocol

internal object AnimationFlag {
    const val NONE: Int = 0
    const val EDGE_SCROLL: Int = 1
    const val FLING: Int = 2
    const val TRANSIENT_SCROLLBAR: Int = 4
}

internal enum class EditorActionSource(val value: Int) {
    NONE(0),
    SETUP(1),
    PROGRAMMATIC(2),
    KEYBOARD(3),
    IME(4),
    GESTURE(5),
    ANIMATION(6),
    DECORATION(7),
    FOLDING(8),
    SEARCH(9),
    LINKED_EDITING(10),
    DIFF(11)
    ;
    companion object {
        fun fromValue(value: Int): EditorActionSource =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown EditorActionSource: $value")
    }
}

internal object InteractionFlag {
    const val NONE: Int = 0
    const val PRIMARY_POINTER: Int = 1
    const val SELECTION_DRAG: Int = 2
    const val VIEWPORT_GESTURE: Int = 4
}

internal enum class ScrollBehavior(val value: Int) {
    GOTO_TOP(0),
    GOTO_CENTER(1),
    GOTO_BOTTOM(2)
    ;
    companion object {
        fun fromValue(value: Int): ScrollBehavior =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown ScrollBehavior: $value")
    }
}

internal enum class TextChangeKind(val value: Int) {
    NONE(0),
    INSERTION(1),
    REPLACEMENT(2),
    DELETION(3),
    MOVE(4),
    UNDO(5),
    REDO(6),
    MIXED(7)
    ;
    companion object {
        fun fromValue(value: Int): TextChangeKind =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown TextChangeKind: $value")
    }
}

internal enum class DiagnosticSeverity(val value: Int) {
    DIAG_ERROR(0),
    DIAG_WARNING(1),
    DIAG_INFO(2),
    DIAG_HINT(3)
    ;
    companion object {
        fun fromValue(value: Int): DiagnosticSeverity =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown DiagnosticSeverity: $value")
    }
}

internal enum class DocumentHighlightKind(val value: Int) {
    TEXT(0),
    READ(1),
    WRITE(2)
    ;
    companion object {
        fun fromValue(value: Int): DocumentHighlightKind =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown DocumentHighlightKind: $value")
    }
}

internal enum class InlayType(val value: Int) {
    TEXT(0),
    ICON(1),
    COLOR(2)
    ;
    companion object {
        fun fromValue(value: Int): InlayType =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown InlayType: $value")
    }
}

internal enum class SeparatorStyle(val value: Int) {
    SINGLE(0),
    DOUBLE(1)
    ;
    companion object {
        fun fromValue(value: Int): SeparatorStyle =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown SeparatorStyle: $value")
    }
}

internal enum class SpanLayer(val value: Int) {
    SYNTAX(0),
    SEMANTIC(1),
    OVERLAY(2)
    ;
    companion object {
        fun fromValue(value: Int): SpanLayer =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown SpanLayer: $value")
    }
}

internal enum class AutoIndentMode(val value: Int) {
    NONE(0),
    KEEP_INDENT(1)
    ;
    companion object {
        fun fromValue(value: Int): AutoIndentMode =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown AutoIndentMode: $value")
    }
}

internal enum class CurrentLineRenderMode(val value: Int) {
    BACKGROUND(0),
    BORDER(1),
    NONE(2)
    ;
    companion object {
        fun fromValue(value: Int): CurrentLineRenderMode =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown CurrentLineRenderMode: $value")
    }
}

internal enum class FoldArrowMode(val value: Int) {
    AUTO(0),
    ALWAYS(1),
    HIDDEN(2)
    ;
    companion object {
        fun fromValue(value: Int): FoldArrowMode =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown FoldArrowMode: $value")
    }
}

internal enum class RangeEffectUnderlineStyle(val value: Int) {
    NONE(0),
    SOLID(1),
    DASHED(2),
    WAVY(3)
    ;
    companion object {
        fun fromValue(value: Int): RangeEffectUnderlineStyle =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown RangeEffectUnderlineStyle: $value")
    }
}

internal enum class ScrollbarMode(val value: Int) {
    ALWAYS(0),
    TRANSIENT(1),
    NEVER(2)
    ;
    companion object {
        fun fromValue(value: Int): ScrollbarMode =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown ScrollbarMode: $value")
    }
}

internal enum class ScrollbarTrackTapMode(val value: Int) {
    JUMP(0),
    DISABLED(1)
    ;
    companion object {
        fun fromValue(value: Int): ScrollbarTrackTapMode =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown ScrollbarTrackTapMode: $value")
    }
}

internal enum class WhitespaceRenderMode(val value: Int) {
    NONE(0),
    BOUNDARY(1),
    SELECTION(2),
    TRAILING(3),
    ALL(4)
    ;
    companion object {
        fun fromValue(value: Int): WhitespaceRenderMode =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown WhitespaceRenderMode: $value")
    }
}

internal enum class WrapMode(val value: Int) {
    NONE(0),
    CHAR_BREAK(1),
    WORD_BREAK(2)
    ;
    companion object {
        fun fromValue(value: Int): WrapMode =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown WrapMode: $value")
    }
}

internal enum class CaretAffinity(val value: Int) {
    DOWNSTREAM(0),
    UPSTREAM(1)
    ;
    companion object {
        fun fromValue(value: Int): CaretAffinity =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown CaretAffinity: $value")
    }
}

internal enum class ImeCommandKind(val value: Int) {
    SET_SELECTION(0),
    BEGIN_COMPOSITION(1),
    UPDATE_COMPOSITION(2),
    COMMIT_TEXT(3),
    FINISH_COMPOSITION(4),
    CANCEL_COMPOSITION(5),
    DELETE_SURROUNDING(6)
    ;
    companion object {
        fun fromValue(value: Int): ImeCommandKind =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown ImeCommandKind: $value")
    }
}

internal enum class ImeCoordinateSpace(val value: Int) {
    DOCUMENT(0),
    EDITING_BUFFER(1),
    CONTEXT_SLICE(2),
    COMPOSITION(3)
    ;
    companion object {
        fun fromValue(value: Int): ImeCoordinateSpace =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown ImeCoordinateSpace: $value")
    }
}

internal enum class ImeHostAction(val value: Int) {
    NONE(0),
    CLOSE_SESSION(1),
    RESTART_SESSION(2),
    SYNC_EDITING_STATE(3)
    ;
    companion object {
        fun fromValue(value: Int): ImeHostAction =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown ImeHostAction: $value")
    }
}

internal enum class ImeMutationModel(val value: Int) {
    COMMAND(0),
    TEXT_UPDATE(1)
    ;
    companion object {
        fun fromValue(value: Int): ImeMutationModel =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown ImeMutationModel: $value")
    }
}

internal enum class ImeResultCode(val value: Int) {
    OK(0),
    SESSION_MISMATCH(1),
    REJECTED(2),
    READ_ONLY(3)
    ;
    companion object {
        fun fromValue(value: Int): ImeResultCode =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown ImeResultCode: $value")
    }
}

internal enum class ImeTextSource(val value: Int) {
    EDITING(0),
    COMMITTED(1),
    EDITING_BUFFER(2)
    ;
    companion object {
        fun fromValue(value: Int): ImeTextSource =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown ImeTextSource: $value")
    }
}

internal enum class ImeTextUnit(val value: Int) {
    UTF16_CODE_UNIT(0),
    UNICODE_CODE_POINT(1)
    ;
    companion object {
        fun fromValue(value: Int): ImeTextUnit =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown ImeTextUnit: $value")
    }
}

internal enum class EventType(val value: Int) {
    UNDEFINED(0),
    TOUCH_DOWN(1),
    TOUCH_POINTER_DOWN(2),
    TOUCH_MOVE(3),
    TOUCH_POINTER_UP(4),
    TOUCH_UP(5),
    TOUCH_CANCEL(6),
    MOUSE_DOWN(7),
    MOUSE_MOVE(8),
    MOUSE_UP(9),
    MOUSE_WHEEL(10),
    MOUSE_RIGHT_DOWN(11),
    DIRECT_SCALE(12),
    DIRECT_SCROLL(13),
    DIRECT_GESTURE_BEGIN(14),
    DIRECT_GESTURE_END(15)
    ;
    companion object {
        fun fromValue(value: Int): EventType =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown EventType: $value")
    }
}

internal enum class GestureType(val value: Int) {
    UNDEFINED(0),
    TAP(1),
    DOUBLE_TAP(2),
    LONG_PRESS(3),
    SCALE(4),
    SCROLL(5),
    FAST_SCROLL(6),
    DRAG_SELECT(7),
    CONTEXT_MENU(8)
    ;
    companion object {
        fun fromValue(value: Int): GestureType =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown GestureType: $value")
    }
}

internal enum class HitTargetType(val value: Int) {
    NONE(0),
    INLAY_HINT_TEXT(1),
    INLAY_HINT_ICON(2),
    INLAY_HINT_COLOR(3),
    CODELENS(4),
    LINK(5),
    GUTTER_ICON(6),
    FOLD_GUTTER(7),
    FOLD_PLACEHOLDER(8)
    ;
    companion object {
        fun fromValue(value: Int): HitTargetType =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown HitTargetType: $value")
    }
}

internal enum class EditorBuiltinCommand(val value: Int) {
    NONE(0),
    CURSOR_LEFT(1),
    CURSOR_RIGHT(2),
    CURSOR_UP(3),
    CURSOR_DOWN(4),
    CURSOR_LINE_START(5),
    CURSOR_LINE_END(6),
    CURSOR_PAGE_UP(7),
    CURSOR_PAGE_DOWN(8),
    SELECT_LEFT(9),
    SELECT_RIGHT(10),
    SELECT_UP(11),
    SELECT_DOWN(12),
    SELECT_LINE_START(13),
    SELECT_LINE_END(14),
    SELECT_PAGE_UP(15),
    SELECT_PAGE_DOWN(16),
    SELECT_ALL(17),
    BACKSPACE(18),
    DELETE_FORWARD(19),
    INSERT_TAB(20),
    INSERT_NEWLINE(21),
    INSERT_LINE_ABOVE(22),
    INSERT_LINE_BELOW(23),
    UNDO(24),
    REDO(25),
    MOVE_LINE_UP(26),
    MOVE_LINE_DOWN(27),
    COPY_LINE_UP(28),
    COPY_LINE_DOWN(29),
    DELETE_LINE(30),
    COPY(31),
    PASTE(32),
    CUT(33),
    TRIGGER_COMPLETION(34)
    ;
    companion object {
        fun fromValue(value: Int): EditorBuiltinCommand =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown EditorBuiltinCommand: $value")
    }
}

internal object KeyCode {
    const val NONE: Int = 0
    const val BACKSPACE: Int = 8
    const val TAB: Int = 9
    const val ENTER: Int = 13
    const val ESCAPE: Int = 27
    const val SPACE: Int = 32
    const val PAGE_UP: Int = 33
    const val PAGE_DOWN: Int = 34
    const val END: Int = 35
    const val HOME: Int = 36
    const val LEFT: Int = 37
    const val UP: Int = 38
    const val RIGHT: Int = 39
    const val DOWN: Int = 40
    const val DELETE_KEY: Int = 46
    const val A: Int = 65
    const val C: Int = 67
    const val D: Int = 68
    const val K: Int = 75
    const val V: Int = 86
    const val X: Int = 88
    const val Y: Int = 89
    const val Z: Int = 90
}

internal object KeyModifier {
    const val NONE: Int = 0
    const val SHIFT: Int = 1
    const val CTRL: Int = 2
    const val ALT: Int = 4
    const val META: Int = 8
}

internal enum class SearchStatus(val value: Int) {
    INACTIVE(0),
    SEARCHING(1),
    READY(2),
    STALE(3),
    FAILED(4)
    ;
    companion object {
        fun fromValue(value: Int): SearchStatus =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown SearchStatus: $value")
    }
}

internal enum class FoldState(val value: Int) {
    NONE(0),
    EXPANDED(1),
    COLLAPSED(2)
    ;
    companion object {
        fun fromValue(value: Int): FoldState =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown FoldState: $value")
    }
}

internal enum class GuideDirection(val value: Int) {
    VERTICAL(0),
    HORIZONTAL(1)
    ;
    companion object {
        fun fromValue(value: Int): GuideDirection =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown GuideDirection: $value")
    }
}

internal enum class GuideStyle(val value: Int) {
    SOLID(0),
    DASHED(1),
    DOUBLE(2)
    ;
    companion object {
        fun fromValue(value: Int): GuideStyle =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown GuideStyle: $value")
    }
}

internal enum class GuideType(val value: Int) {
    INDENT(0),
    BRACKET(1),
    FLOW(2),
    SEPARATOR(3)
    ;
    companion object {
        fun fromValue(value: Int): GuideType =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown GuideType: $value")
    }
}

internal enum class PointerCursorType(val value: Int) {
    DEFAULT(0),
    TEXT(1),
    HAND(2)
    ;
    companion object {
        fun fromValue(value: Int): PointerCursorType =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown PointerCursorType: $value")
    }
}

internal enum class RangeEffectKind(val value: Int) {
    SELECTION(0),
    SEARCH_MATCH(1),
    SEARCH_CURRENT(2),
    DOCUMENT_HIGHLIGHT_TEXT(3),
    DOCUMENT_HIGHLIGHT_READ(4),
    DOCUMENT_HIGHLIGHT_WRITE(5),
    LINKED_EDITING_ACTIVE(6),
    LINKED_EDITING_INACTIVE(7),
    IME_COMPOSITION(8),
    BRACKET_MATCH(9),
    DIAGNOSTIC_ERROR(10),
    DIAGNOSTIC_WARNING(11),
    DIAGNOSTIC_INFO(12),
    DIAGNOSTIC_HINT(13)
    ;
    companion object {
        fun fromValue(value: Int): RangeEffectKind =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown RangeEffectKind: $value")
    }
}

internal enum class VisualLineKind(val value: Int) {
    CONTENT(0),
    PHANTOM(1),
    CODELENS(2),
    REMOVED(3)
    ;
    companion object {
        fun fromValue(value: Int): VisualLineKind =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown VisualLineKind: $value")
    }
}

internal enum class VisualRunType(val value: Int) {
    TEXT(0),
    WHITESPACE(1),
    TAB(2),
    NEWLINE(3),
    INLAY_HINT(4),
    PHANTOM_TEXT(5),
    FOLD_PLACEHOLDER(6),
    CODELENS(7),
    LINK(8)
    ;
    companion object {
        fun fromValue(value: Int): VisualRunType =
            entries.find { it.value == value }
                ?: throw IllegalArgumentException("Unknown VisualRunType: $value")
    }
}

internal data class EditorActionResult(
    val handled: Boolean,
    val needsRedraw: Boolean,
    val source: EditorActionSource,
    val textChangeKind: TextChangeKind,
    val cursorChanged: Boolean,
    val selectionChanged: Boolean,
    val scrollChanged: Boolean,
    val scaleChanged: Boolean,
    val pointerCursorChanged: Boolean,
    val compositionChanged: Boolean,
    val decorationChanged: Boolean,
    val animationFlags: Int,
    val nextAnimationDelayMs: Int,
    val interactionFlags: Int,
    val textChanges: List<TextChange>,
    val cursorBefore: TextPosition,
    val cursorAfter: TextPosition,
    val hasSelectionBefore: Boolean,
    val hasSelectionAfter: Boolean,
    val selectionBefore: TextRange,
    val selectionAfter: TextRange,
    val scrollXBefore: Float,
    val scrollYBefore: Float,
    val scrollXAfter: Float,
    val scrollYAfter: Float,
    val scaleBefore: Float,
    val scaleAfter: Float,
    val pointerCursorBefore: PointerCursorType,
    val pointerCursorAfter: PointerCursorType,
    val imeHostAction: ImeHostAction,
    val imeState: ImeState,
    val gestureType: GestureType,
    val gestureEventType: EventType,
    val tapPoint: PointF,
    val hitTarget: HitTarget,
    val modifiers: Int,
    val command: Int,
)

internal data class BracketGuide(
    val parent: TextPosition,
    val end: TextPosition,
    val children: List<TextPosition>,
)

internal data class CodeLensItem(
    val column: Int,
    val commandId: Int,
    val text: String,
)

internal data class Diagnostic(
    val column: Int,
    val length: Int,
    val severity: DiagnosticSeverity,
)

internal data class DiffChange(
    val currentStartLine: Int,
    val currentLineCount: Int,
    val originalStartLine: Int,
    val removedLines: List<String>,
)

internal data class DocumentHighlight(
    val column: Int,
    val length: Int,
    val kind: DocumentHighlightKind,
)

internal data class FlowGuide(
    val start: TextPosition,
    val end: TextPosition,
)

internal data class FoldRegion(
    val startLine: Int,
    val endLine: Int,
    val collapsed: Boolean,
)

internal data class GutterIcon(
    val iconId: Int,
)

internal data class IndentGuide(
    val start: TextPosition,
    val end: TextPosition,
)

internal data class InlayHint(
    val `type`: InlayType,
    val column: Int,
    val intValue: Int,
    val text: String,
)

internal data class LinkSpan(
    val column: Int,
    val length: Int,
    val target: String,
)

internal data class PhantomText(
    val column: Int,
    val text: String,
)

internal data class SeparatorGuide(
    val line: Int,
    val style: SeparatorStyle,
    val count: Int,
    val textEndColumn: Int,
)

internal data class StyleSpan(
    val column: Int,
    val length: Int,
    val styleId: Int,
)

internal data class TextStyle(
    val color: Int,
    val backgroundColor: Int,
    val fontStyle: Int,
)

internal data class EditorOptions(
    val touchSlop: Float,
    val doubleTapTimeout: Long,
    val longPressMs: Long,
    val flingFriction: Float,
    val flingMinVelocity: Float,
    val flingMaxVelocity: Float,
    val maxUndoStackSize: Long,
    val keyChordTimeoutMs: Long,
    val revealSelectionEndOnSelectAll: Boolean,
)

internal data class EditorRangeEffectStyles(
    val selection: RangeEffectStyle,
    val searchMatch: RangeEffectStyle,
    val searchCurrent: RangeEffectStyle,
    val documentHighlightText: RangeEffectStyle,
    val documentHighlightRead: RangeEffectStyle,
    val documentHighlightWrite: RangeEffectStyle,
    val linkedEditingActive: RangeEffectStyle,
    val linkedEditingInactive: RangeEffectStyle,
    val imeComposition: RangeEffectStyle,
    val bracketMatch: RangeEffectStyle,
    val diagnosticError: RangeEffectStyle,
    val diagnosticWarning: RangeEffectStyle,
    val diagnosticInfo: RangeEffectStyle,
    val diagnosticHint: RangeEffectStyle,
)

internal data class EditorRenderColors(
    val textForeground: Int,
    val linkForeground: Int,
    val activeLinkForeground: Int,
    val codelensForeground: Int,
    val activeCodelensForeground: Int,
    val diffAddedLineBackground: Int,
    val diffRemovedLineBackground: Int,
    val diffAddedGutterBackground: Int,
    val diffRemovedGutterBackground: Int,
)

internal data class HandleConfig(
    val startHitArea: HandleHitArea,
    val endHitArea: HandleHitArea,
)

internal data class HandleHitArea(
    val left: Float,
    val top: Float,
    val right: Float,
    val bottom: Float,
)

internal data class RangeEffectStyle(
    val foregroundColor: Int,
    val backgroundColor: Int,
    val borderColor: Int,
    val underlineColor: Int,
    val underlineStyle: RangeEffectUnderlineStyle,
)

internal data class ScrollbarConfig(
    val thickness: Float,
    val minThumb: Float,
    val thumbHitPadding: Float,
    val mode: ScrollbarMode,
    val thumbDraggable: Boolean,
    val trackTapMode: ScrollbarTrackTapMode,
    val fadeDelayMs: Int,
    val fadeDurationMs: Int,
)

internal data class IntRange(
    val start: Int,
    val end: Int,
)

internal data class PointF(
    val x: Float,
    val y: Float,
)

internal data class Rect(
    val origin: PointF,
    val width: Float,
    val height: Float,
)

internal data class Size(
    val width: Float,
    val height: Float,
)

internal data class TabStopGroup(
    val index: Int,
    val ranges: List<TextRange>,
    val defaultText: String,
)

internal data class TextChange(
    val range: TextRange,
    val newText: String,
)

internal data class TextEdit(
    val range: TextRange,
    val newText: String,
)

internal data class TextPosition(
    val line: Int,
    val column: Int,
)

internal data class TextRange(
    val start: TextPosition,
    val end: TextPosition,
)

internal data class ImeCommand(
    val kind: ImeCommandKind,
    val targetRange: ImeOffsetRange,
    val selectionAfter: ImeSelection,
    val text: String,
    val deleteBefore: Long,
    val deleteAfter: Long,
    val textUnit: ImeTextUnit,
)

internal data class ImeCommandBatch(
    val sessionId: Long,
    val commands: List<ImeCommand>,
)

internal data class ImeOffsetRange(
    val coordinateSpace: ImeCoordinateSpace,
    val startUtf16: Long,
    val endUtf16: Long,
)

internal data class ImeSelection(
    val coordinateSpace: ImeCoordinateSpace,
    val anchorUtf16: Long,
    val activeUtf16: Long,
    val affinity: CaretAffinity,
)

internal data class ImeState(
    val resultCode: ImeResultCode,
    val sessionId: Long,
    val stateRevision: Long,
    val selection: ImeSelection,
    val compositionRange: ImeOffsetRange,
)

internal data class ImeTextContext(
    val resultCode: ImeResultCode,
    val sliceStartUtf16: Long,
    val totalLengthUtf16: Long,
    val text: String,
    val selection: ImeSelection,
    val compositionRange: ImeOffsetRange,
)

internal data class ImeTextUpdateBatch(
    val sessionId: Long,
    val expectedStateRevision: Long,
    val steps: List<ImeTextUpdateStep>,
)

internal data class ImeTextUpdateStep(
    val oldText: String,
    val patchRange: ImeOffsetRange,
    val replacementText: String,
    val selectionAfter: ImeSelection,
    val compositionAfter: ImeOffsetRange,
)

internal data class GestureEvent(
    val `type`: EventType,
    val points: List<PointF>,
    val modifiers: Int,
    val wheelDeltaX: Float,
    val wheelDeltaY: Float,
    val directScale: Float,
)

internal data class HitTarget(
    val `type`: HitTargetType,
    val line: Int,
    val column: Int,
    val iconId: Int,
    val colorValue: Int,
)

internal data class KeyBinding(
    val first: KeyChord,
    val second: KeyChord,
    val command: Int,
)

internal data class KeyChord(
    val modifiers: Int,
    val keyCode: Int,
)

internal data class SearchOptions(
    val caseSensitive: Boolean,
    val wholeWord: Boolean,
    val useRegex: Boolean,
    val wrapAround: Boolean,
    val maxMatches: Int,
)

internal data class SearchRequest(
    val pattern: String,
    val options: SearchOptions,
)

internal data class SearchState(
    val status: SearchStatus,
    val pattern: String,
    val options: SearchOptions,
    val generation: Long,
    val matchCount: Int,
    val currentIndex: Int,
    val hasCurrentMatch: Boolean,
    val currentRange: TextRange,
    val errorMessage: String,
)

internal data class Cursor(
    val textPosition: TextPosition,
    val position: PointF,
    val height: Float,
    val visible: Boolean,
    val showDragger: Boolean,
)

internal data class CursorRect(
    val x: Float,
    val y: Float,
    val height: Float,
)

internal data class EditorRenderModel(
    val splitX: Float,
    val splitLineVisible: Boolean,
    val scrollX: Float,
    val scrollY: Float,
    val viewportSize: Size,
    val currentLine: PointF,
    val currentLineRenderMode: CurrentLineRenderMode,
    val lines: List<VisualLine>,
    val cursor: Cursor,
    val rangeEffects: List<RangeEffectRenderItem>,
    val selectionStartHandle: SelectionHandle,
    val selectionEndHandle: SelectionHandle,
    val guideSegments: List<GuideSegment>,
    val maxGutterIcons: Int,
    val gutterIcons: List<GutterIconRenderItem>,
    val foldMarkers: List<FoldMarkerRenderItem>,
    val verticalScrollbar: ScrollbarModel,
    val horizontalScrollbar: ScrollbarModel,
    val gutterSticky: Boolean,
    val gutterVisible: Boolean,
    val pointerCursorType: PointerCursorType,
)

internal data class FoldMarkerRenderItem(
    val logicalLine: Int,
    val foldState: FoldState,
    val rect: Rect,
)

internal data class GuideSegment(
    val direction: GuideDirection,
    val `type`: GuideType,
    val style: GuideStyle,
    val start: PointF,
    val end: PointF,
    val arrowEnd: Boolean,
)

internal data class GutterIconRenderItem(
    val logicalLine: Int,
    val iconId: Int,
    val rect: Rect,
)

internal data class LayoutMetrics(
    val fontHeight: Float,
    val fontAscent: Float,
    val lineSpacingAdd: Float,
    val lineSpacingMult: Float,
    val lineNumberMargin: Float,
    val lineNumberWidth: Float,
    val contentStartPadding: Float,
    val maxGutterIcons: Int,
    val inlayHintPadding: Float,
    val inlayHintMargin: Float,
    val foldArrowMode: FoldArrowMode,
    val hasFoldRegions: Boolean,
    val gutterSticky: Boolean,
    val gutterVisible: Boolean,
)

internal data class RangeEffectRenderItem(
    val rect: Rect,
    val kind: RangeEffectKind,
    val style: RangeEffectStyle,
)

internal data class ScrollMetrics(
    val scale: Float,
    val scrollX: Float,
    val scrollY: Float,
    val maxScrollX: Float,
    val maxScrollY: Float,
    val contentSize: Size,
    val viewportSize: Size,
    val textAreaX: Float,
    val textAreaWidth: Float,
    val canScrollX: Boolean,
    val canScrollY: Boolean,
)

internal data class ScrollbarModel(
    val visible: Boolean,
    val alpha: Float,
    val thumbActive: Boolean,
    val track: Rect,
    val thumb: Rect,
)

internal data class SelectionHandle(
    val position: PointF,
    val height: Float,
    val visible: Boolean,
)

internal data class VisualLine(
    val logicalLine: Int,
    val wrapIndex: Int,
    val lineNumberPosition: PointF,
    val runs: List<VisualRun>,
    val kind: VisualLineKind,
    val ownsGutterSemantics: Boolean,
    val foldState: FoldState,
    val lineNumber: Int,
    val lineBackgroundColor: Int,
    val gutterBackgroundColor: Int,
)

internal data class VisualRun(
    val `type`: VisualRunType,
    val x: Float,
    val y: Float,
    val text: String,
    val style: TextStyle,
    val iconId: Int,
    val colorValue: Int,
    val width: Float,
    val padding: Float,
    val margin: Float,
    val active: Boolean,
)

internal object CoreProtocol {
    fun decodeEditorActionResult(bytes: ByteArray): EditorActionResult = readEditorActionResult(ProtocolReader(bytes))
    private fun readEditorActionResult(reader: ProtocolReader): EditorActionResult {
        val handled = reader.readBoolI32()
        val needsRedraw = reader.readBoolI32()
        val source = EditorActionSource.fromValue(reader.readI32())
        val textChangeKind = TextChangeKind.fromValue(reader.readI32())
        val cursorChanged = reader.readBoolI32()
        val selectionChanged = reader.readBoolI32()
        val scrollChanged = reader.readBoolI32()
        val scaleChanged = reader.readBoolI32()
        val pointerCursorChanged = reader.readBoolI32()
        val compositionChanged = reader.readBoolI32()
        val decorationChanged = reader.readBoolI32()
        val animationFlags = reader.readU32()
        val nextAnimationDelayMs = reader.readU32()
        val interactionFlags = reader.readU32()
        val textChanges = readListTextChange(reader)
        val cursorBefore = readTextPosition(reader)
        val cursorAfter = readTextPosition(reader)
        val hasSelectionBefore = reader.readBoolI32()
        val hasSelectionAfter = reader.readBoolI32()
        val selectionBefore = readTextRange(reader)
        val selectionAfter = readTextRange(reader)
        val scrollXBefore = reader.readF32()
        val scrollYBefore = reader.readF32()
        val scrollXAfter = reader.readF32()
        val scrollYAfter = reader.readF32()
        val scaleBefore = reader.readF32()
        val scaleAfter = reader.readF32()
        val pointerCursorBefore = PointerCursorType.fromValue(reader.readI32())
        val pointerCursorAfter = PointerCursorType.fromValue(reader.readI32())
        val imeHostAction = ImeHostAction.fromValue(reader.readI32())
        val imeState = readImeState(reader)
        val gestureType = GestureType.fromValue(reader.readI32())
        val gestureEventType = EventType.fromValue(reader.readI32())
        val tapPoint = readPointF(reader)
        val hitTarget = readHitTarget(reader)
        val modifiers = reader.readI32()
        val command = reader.readI32()
        return EditorActionResult(handled, needsRedraw, source, textChangeKind, cursorChanged, selectionChanged, scrollChanged, scaleChanged, pointerCursorChanged, compositionChanged, decorationChanged, animationFlags, nextAnimationDelayMs, interactionFlags, textChanges, cursorBefore, cursorAfter, hasSelectionBefore, hasSelectionAfter, selectionBefore, selectionAfter, scrollXBefore, scrollYBefore, scrollXAfter, scrollYAfter, scaleBefore, scaleAfter, pointerCursorBefore, pointerCursorAfter, imeHostAction, imeState, gestureType, gestureEventType, tapPoint, hitTarget, modifiers, command)
    }
    private fun writeEditorActionResult(writer: ProtocolWriter, value: EditorActionResult) {
        writer.writeBoolI32(value.handled)
        writer.writeBoolI32(value.needsRedraw)
        writer.writeI32(value.source.value)
        writer.writeI32(value.textChangeKind.value)
        writer.writeBoolI32(value.cursorChanged)
        writer.writeBoolI32(value.selectionChanged)
        writer.writeBoolI32(value.scrollChanged)
        writer.writeBoolI32(value.scaleChanged)
        writer.writeBoolI32(value.pointerCursorChanged)
        writer.writeBoolI32(value.compositionChanged)
        writer.writeBoolI32(value.decorationChanged)
        writer.writeU32(value.animationFlags)
        writer.writeU32(value.nextAnimationDelayMs)
        writer.writeU32(value.interactionFlags)
        writeListTextChange(writer, value.textChanges)
        writeTextPosition(writer, value.cursorBefore)
        writeTextPosition(writer, value.cursorAfter)
        writer.writeBoolI32(value.hasSelectionBefore)
        writer.writeBoolI32(value.hasSelectionAfter)
        writeTextRange(writer, value.selectionBefore)
        writeTextRange(writer, value.selectionAfter)
        writer.writeF32(value.scrollXBefore)
        writer.writeF32(value.scrollYBefore)
        writer.writeF32(value.scrollXAfter)
        writer.writeF32(value.scrollYAfter)
        writer.writeF32(value.scaleBefore)
        writer.writeF32(value.scaleAfter)
        writer.writeI32(value.pointerCursorBefore.value)
        writer.writeI32(value.pointerCursorAfter.value)
        writer.writeI32(value.imeHostAction.value)
        writeImeState(writer, value.imeState)
        writer.writeI32(value.gestureType.value)
        writer.writeI32(value.gestureEventType.value)
        writePointF(writer, value.tapPoint)
        writeHitTarget(writer, value.hitTarget)
        writer.writeI32(value.modifiers)
        writer.writeI32(value.command)
    }
    private fun readBracketGuide(reader: ProtocolReader): BracketGuide {
        val parent = readTextPosition(reader)
        val end = readTextPosition(reader)
        val children = readListTextPosition(reader)
        return BracketGuide(parent, end, children)
    }
    fun encodeBracketGuide(value: BracketGuide): ByteArray {
        val writer = ProtocolWriter()
        writeBracketGuide(writer, value)
        return writer.toByteArray()
    }
    private fun writeBracketGuide(writer: ProtocolWriter, value: BracketGuide) {
        writeTextPosition(writer, value.parent)
        writeTextPosition(writer, value.end)
        writeListTextPosition(writer, value.children)
    }
    private fun readCodeLensItem(reader: ProtocolReader): CodeLensItem {
        val column = reader.readI32()
        val commandId = reader.readI32()
        val text = reader.readUtf8String()
        return CodeLensItem(column, commandId, text)
    }
    fun encodeCodeLensItem(value: CodeLensItem): ByteArray {
        val writer = ProtocolWriter()
        writeCodeLensItem(writer, value)
        return writer.toByteArray()
    }
    private fun writeCodeLensItem(writer: ProtocolWriter, value: CodeLensItem) {
        writer.writeI32(value.column)
        writer.writeI32(value.commandId)
        writer.writeUtf8String(value.text)
    }
    private fun readDiagnostic(reader: ProtocolReader): Diagnostic {
        val column = reader.readU32()
        val length = reader.readU32()
        val severity = DiagnosticSeverity.fromValue(reader.readI32())
        return Diagnostic(column, length, severity)
    }
    fun encodeDiagnostic(value: Diagnostic): ByteArray {
        val writer = ProtocolWriter()
        writeDiagnostic(writer, value)
        return writer.toByteArray()
    }
    private fun writeDiagnostic(writer: ProtocolWriter, value: Diagnostic) {
        writer.writeU32(value.column)
        writer.writeU32(value.length)
        writer.writeI32(value.severity.value)
    }
    private fun readDiffChange(reader: ProtocolReader): DiffChange {
        val currentStartLine = reader.readU32()
        val currentLineCount = reader.readU32()
        val originalStartLine = reader.readU32()
        val removedLines = readListU8String(reader)
        return DiffChange(currentStartLine, currentLineCount, originalStartLine, removedLines)
    }
    fun encodeDiffChange(value: DiffChange): ByteArray {
        val writer = ProtocolWriter()
        writeDiffChange(writer, value)
        return writer.toByteArray()
    }
    private fun writeDiffChange(writer: ProtocolWriter, value: DiffChange) {
        writer.writeU32(value.currentStartLine)
        writer.writeU32(value.currentLineCount)
        writer.writeU32(value.originalStartLine)
        writeListU8String(writer, value.removedLines)
    }
    private fun readDocumentHighlight(reader: ProtocolReader): DocumentHighlight {
        val column = reader.readU32()
        val length = reader.readU32()
        val kind = DocumentHighlightKind.fromValue(reader.readI32())
        return DocumentHighlight(column, length, kind)
    }
    fun encodeDocumentHighlight(value: DocumentHighlight): ByteArray {
        val writer = ProtocolWriter()
        writeDocumentHighlight(writer, value)
        return writer.toByteArray()
    }
    private fun writeDocumentHighlight(writer: ProtocolWriter, value: DocumentHighlight) {
        writer.writeU32(value.column)
        writer.writeU32(value.length)
        writer.writeI32(value.kind.value)
    }
    private fun readFlowGuide(reader: ProtocolReader): FlowGuide {
        val start = readTextPosition(reader)
        val end = readTextPosition(reader)
        return FlowGuide(start, end)
    }
    fun encodeFlowGuide(value: FlowGuide): ByteArray {
        val writer = ProtocolWriter()
        writeFlowGuide(writer, value)
        return writer.toByteArray()
    }
    private fun writeFlowGuide(writer: ProtocolWriter, value: FlowGuide) {
        writeTextPosition(writer, value.start)
        writeTextPosition(writer, value.end)
    }
    private fun readFoldRegion(reader: ProtocolReader): FoldRegion {
        val startLine = reader.readU32()
        val endLine = reader.readU32()
        val collapsed = reader.readBoolU8()
        return FoldRegion(startLine, endLine, collapsed)
    }
    fun encodeFoldRegion(value: FoldRegion): ByteArray {
        val writer = ProtocolWriter()
        writeFoldRegion(writer, value)
        return writer.toByteArray()
    }
    private fun writeFoldRegion(writer: ProtocolWriter, value: FoldRegion) {
        writer.writeU32(value.startLine)
        writer.writeU32(value.endLine)
        writer.writeBoolU8(value.collapsed)
    }
    private fun readGutterIcon(reader: ProtocolReader): GutterIcon {
        val iconId = reader.readI32()
        return GutterIcon(iconId)
    }
    fun encodeGutterIcon(value: GutterIcon): ByteArray {
        val writer = ProtocolWriter()
        writeGutterIcon(writer, value)
        return writer.toByteArray()
    }
    private fun writeGutterIcon(writer: ProtocolWriter, value: GutterIcon) {
        writer.writeI32(value.iconId)
    }
    private fun readIndentGuide(reader: ProtocolReader): IndentGuide {
        val start = readTextPosition(reader)
        val end = readTextPosition(reader)
        return IndentGuide(start, end)
    }
    fun encodeIndentGuide(value: IndentGuide): ByteArray {
        val writer = ProtocolWriter()
        writeIndentGuide(writer, value)
        return writer.toByteArray()
    }
    private fun writeIndentGuide(writer: ProtocolWriter, value: IndentGuide) {
        writeTextPosition(writer, value.start)
        writeTextPosition(writer, value.end)
    }
    private fun readInlayHint(reader: ProtocolReader): InlayHint {
        val `type` = InlayType.fromValue(reader.readI32())
        val column = reader.readU32()
        val intValue = reader.readI32()
        val text = reader.readUtf8String()
        return InlayHint(`type`, column, intValue, text)
    }
    fun encodeInlayHint(value: InlayHint): ByteArray {
        val writer = ProtocolWriter()
        writeInlayHint(writer, value)
        return writer.toByteArray()
    }
    private fun writeInlayHint(writer: ProtocolWriter, value: InlayHint) {
        writer.writeI32(value.`type`.value)
        writer.writeU32(value.column)
        writer.writeI32(value.intValue)
        writer.writeUtf8String(value.text)
    }
    private fun readLinkSpan(reader: ProtocolReader): LinkSpan {
        val column = reader.readU32()
        val length = reader.readU32()
        val target = reader.readUtf8String()
        return LinkSpan(column, length, target)
    }
    fun encodeLinkSpan(value: LinkSpan): ByteArray {
        val writer = ProtocolWriter()
        writeLinkSpan(writer, value)
        return writer.toByteArray()
    }
    private fun writeLinkSpan(writer: ProtocolWriter, value: LinkSpan) {
        writer.writeU32(value.column)
        writer.writeU32(value.length)
        writer.writeUtf8String(value.target)
    }
    private fun readPhantomText(reader: ProtocolReader): PhantomText {
        val column = reader.readU32()
        val text = reader.readUtf8String()
        return PhantomText(column, text)
    }
    fun encodePhantomText(value: PhantomText): ByteArray {
        val writer = ProtocolWriter()
        writePhantomText(writer, value)
        return writer.toByteArray()
    }
    private fun writePhantomText(writer: ProtocolWriter, value: PhantomText) {
        writer.writeU32(value.column)
        writer.writeUtf8String(value.text)
    }
    private fun readSeparatorGuide(reader: ProtocolReader): SeparatorGuide {
        val line = reader.readI32()
        val style = SeparatorStyle.fromValue(reader.readI32())
        val count = reader.readI32()
        val textEndColumn = reader.readU32()
        return SeparatorGuide(line, style, count, textEndColumn)
    }
    fun encodeSeparatorGuide(value: SeparatorGuide): ByteArray {
        val writer = ProtocolWriter()
        writeSeparatorGuide(writer, value)
        return writer.toByteArray()
    }
    private fun writeSeparatorGuide(writer: ProtocolWriter, value: SeparatorGuide) {
        writer.writeI32(value.line)
        writer.writeI32(value.style.value)
        writer.writeI32(value.count)
        writer.writeU32(value.textEndColumn)
    }
    fun decodeStyleSpan(bytes: ByteArray): StyleSpan = readStyleSpan(ProtocolReader(bytes))
    private fun readStyleSpan(reader: ProtocolReader): StyleSpan {
        val column = reader.readU32()
        val length = reader.readU32()
        val styleId = reader.readU32()
        return StyleSpan(column, length, styleId)
    }
    fun encodeStyleSpan(value: StyleSpan): ByteArray {
        val writer = ProtocolWriter()
        writeStyleSpan(writer, value)
        return writer.toByteArray()
    }
    private fun writeStyleSpan(writer: ProtocolWriter, value: StyleSpan) {
        writer.writeU32(value.column)
        writer.writeU32(value.length)
        writer.writeU32(value.styleId)
    }
    fun decodeTextStyle(bytes: ByteArray): TextStyle = readTextStyle(ProtocolReader(bytes))
    private fun readTextStyle(reader: ProtocolReader): TextStyle {
        val color = reader.readI32()
        val backgroundColor = reader.readI32()
        val fontStyle = reader.readI32()
        return TextStyle(color, backgroundColor, fontStyle)
    }
    fun encodeTextStyle(value: TextStyle): ByteArray {
        val writer = ProtocolWriter()
        writeTextStyle(writer, value)
        return writer.toByteArray()
    }
    private fun writeTextStyle(writer: ProtocolWriter, value: TextStyle) {
        writer.writeI32(value.color)
        writer.writeI32(value.backgroundColor)
        writer.writeI32(value.fontStyle)
    }
    private fun readEditorOptions(reader: ProtocolReader): EditorOptions {
        val touchSlop = reader.readF32()
        val doubleTapTimeout = reader.readI64()
        val longPressMs = reader.readI64()
        val flingFriction = reader.readF32()
        val flingMinVelocity = reader.readF32()
        val flingMaxVelocity = reader.readF32()
        val maxUndoStackSize = reader.readU64()
        val keyChordTimeoutMs = reader.readI64()
        val revealSelectionEndOnSelectAll = reader.readBoolU8()
        return EditorOptions(touchSlop, doubleTapTimeout, longPressMs, flingFriction, flingMinVelocity, flingMaxVelocity, maxUndoStackSize, keyChordTimeoutMs, revealSelectionEndOnSelectAll)
    }
    fun encodeEditorOptions(value: EditorOptions): ByteArray {
        val writer = ProtocolWriter()
        writeEditorOptions(writer, value)
        return writer.toByteArray()
    }
    private fun writeEditorOptions(writer: ProtocolWriter, value: EditorOptions) {
        writer.writeF32(value.touchSlop)
        writer.writeI64(value.doubleTapTimeout)
        writer.writeI64(value.longPressMs)
        writer.writeF32(value.flingFriction)
        writer.writeF32(value.flingMinVelocity)
        writer.writeF32(value.flingMaxVelocity)
        writer.writeU64(value.maxUndoStackSize)
        writer.writeI64(value.keyChordTimeoutMs)
        writer.writeBoolU8(value.revealSelectionEndOnSelectAll)
    }
    private fun readEditorRangeEffectStyles(reader: ProtocolReader): EditorRangeEffectStyles {
        val selection = readRangeEffectStyle(reader)
        val searchMatch = readRangeEffectStyle(reader)
        val searchCurrent = readRangeEffectStyle(reader)
        val documentHighlightText = readRangeEffectStyle(reader)
        val documentHighlightRead = readRangeEffectStyle(reader)
        val documentHighlightWrite = readRangeEffectStyle(reader)
        val linkedEditingActive = readRangeEffectStyle(reader)
        val linkedEditingInactive = readRangeEffectStyle(reader)
        val imeComposition = readRangeEffectStyle(reader)
        val bracketMatch = readRangeEffectStyle(reader)
        val diagnosticError = readRangeEffectStyle(reader)
        val diagnosticWarning = readRangeEffectStyle(reader)
        val diagnosticInfo = readRangeEffectStyle(reader)
        val diagnosticHint = readRangeEffectStyle(reader)
        return EditorRangeEffectStyles(selection, searchMatch, searchCurrent, documentHighlightText, documentHighlightRead, documentHighlightWrite, linkedEditingActive, linkedEditingInactive, imeComposition, bracketMatch, diagnosticError, diagnosticWarning, diagnosticInfo, diagnosticHint)
    }
    fun encodeEditorRangeEffectStyles(value: EditorRangeEffectStyles): ByteArray {
        val writer = ProtocolWriter()
        writeEditorRangeEffectStyles(writer, value)
        return writer.toByteArray()
    }
    private fun writeEditorRangeEffectStyles(writer: ProtocolWriter, value: EditorRangeEffectStyles) {
        writeRangeEffectStyle(writer, value.selection)
        writeRangeEffectStyle(writer, value.searchMatch)
        writeRangeEffectStyle(writer, value.searchCurrent)
        writeRangeEffectStyle(writer, value.documentHighlightText)
        writeRangeEffectStyle(writer, value.documentHighlightRead)
        writeRangeEffectStyle(writer, value.documentHighlightWrite)
        writeRangeEffectStyle(writer, value.linkedEditingActive)
        writeRangeEffectStyle(writer, value.linkedEditingInactive)
        writeRangeEffectStyle(writer, value.imeComposition)
        writeRangeEffectStyle(writer, value.bracketMatch)
        writeRangeEffectStyle(writer, value.diagnosticError)
        writeRangeEffectStyle(writer, value.diagnosticWarning)
        writeRangeEffectStyle(writer, value.diagnosticInfo)
        writeRangeEffectStyle(writer, value.diagnosticHint)
    }
    private fun readEditorRenderColors(reader: ProtocolReader): EditorRenderColors {
        val textForeground = reader.readI32()
        val linkForeground = reader.readI32()
        val activeLinkForeground = reader.readI32()
        val codelensForeground = reader.readI32()
        val activeCodelensForeground = reader.readI32()
        val diffAddedLineBackground = reader.readI32()
        val diffRemovedLineBackground = reader.readI32()
        val diffAddedGutterBackground = reader.readI32()
        val diffRemovedGutterBackground = reader.readI32()
        return EditorRenderColors(textForeground, linkForeground, activeLinkForeground, codelensForeground, activeCodelensForeground, diffAddedLineBackground, diffRemovedLineBackground, diffAddedGutterBackground, diffRemovedGutterBackground)
    }
    fun encodeEditorRenderColors(value: EditorRenderColors): ByteArray {
        val writer = ProtocolWriter()
        writeEditorRenderColors(writer, value)
        return writer.toByteArray()
    }
    private fun writeEditorRenderColors(writer: ProtocolWriter, value: EditorRenderColors) {
        writer.writeI32(value.textForeground)
        writer.writeI32(value.linkForeground)
        writer.writeI32(value.activeLinkForeground)
        writer.writeI32(value.codelensForeground)
        writer.writeI32(value.activeCodelensForeground)
        writer.writeI32(value.diffAddedLineBackground)
        writer.writeI32(value.diffRemovedLineBackground)
        writer.writeI32(value.diffAddedGutterBackground)
        writer.writeI32(value.diffRemovedGutterBackground)
    }
    private fun readHandleConfig(reader: ProtocolReader): HandleConfig {
        val startHitArea = readHandleHitArea(reader)
        val endHitArea = readHandleHitArea(reader)
        return HandleConfig(startHitArea, endHitArea)
    }
    fun encodeHandleConfig(value: HandleConfig): ByteArray {
        val writer = ProtocolWriter()
        writeHandleConfig(writer, value)
        return writer.toByteArray()
    }
    private fun writeHandleConfig(writer: ProtocolWriter, value: HandleConfig) {
        writeHandleHitArea(writer, value.startHitArea)
        writeHandleHitArea(writer, value.endHitArea)
    }
    fun decodeHandleHitArea(bytes: ByteArray): HandleHitArea = readHandleHitArea(ProtocolReader(bytes))
    private fun readHandleHitArea(reader: ProtocolReader): HandleHitArea {
        val left = reader.readF32()
        val top = reader.readF32()
        val right = reader.readF32()
        val bottom = reader.readF32()
        return HandleHitArea(left, top, right, bottom)
    }
    fun encodeHandleHitArea(value: HandleHitArea): ByteArray {
        val writer = ProtocolWriter()
        writeHandleHitArea(writer, value)
        return writer.toByteArray()
    }
    private fun writeHandleHitArea(writer: ProtocolWriter, value: HandleHitArea) {
        writer.writeF32(value.left)
        writer.writeF32(value.top)
        writer.writeF32(value.right)
        writer.writeF32(value.bottom)
    }
    fun decodeRangeEffectStyle(bytes: ByteArray): RangeEffectStyle = readRangeEffectStyle(ProtocolReader(bytes))
    private fun readRangeEffectStyle(reader: ProtocolReader): RangeEffectStyle {
        val foregroundColor = reader.readI32()
        val backgroundColor = reader.readI32()
        val borderColor = reader.readI32()
        val underlineColor = reader.readI32()
        val underlineStyle = RangeEffectUnderlineStyle.fromValue(reader.readI32())
        return RangeEffectStyle(foregroundColor, backgroundColor, borderColor, underlineColor, underlineStyle)
    }
    fun encodeRangeEffectStyle(value: RangeEffectStyle): ByteArray {
        val writer = ProtocolWriter()
        writeRangeEffectStyle(writer, value)
        return writer.toByteArray()
    }
    private fun writeRangeEffectStyle(writer: ProtocolWriter, value: RangeEffectStyle) {
        writer.writeI32(value.foregroundColor)
        writer.writeI32(value.backgroundColor)
        writer.writeI32(value.borderColor)
        writer.writeI32(value.underlineColor)
        writer.writeI32(value.underlineStyle.value)
    }
    private fun readScrollbarConfig(reader: ProtocolReader): ScrollbarConfig {
        val thickness = reader.readF32()
        val minThumb = reader.readF32()
        val thumbHitPadding = reader.readF32()
        val mode = ScrollbarMode.fromValue(reader.readI32())
        val thumbDraggable = reader.readBoolU8()
        val trackTapMode = ScrollbarTrackTapMode.fromValue(reader.readI32())
        val fadeDelayMs = reader.readU16()
        val fadeDurationMs = reader.readU16()
        return ScrollbarConfig(thickness, minThumb, thumbHitPadding, mode, thumbDraggable, trackTapMode, fadeDelayMs, fadeDurationMs)
    }
    fun encodeScrollbarConfig(value: ScrollbarConfig): ByteArray {
        val writer = ProtocolWriter()
        writeScrollbarConfig(writer, value)
        return writer.toByteArray()
    }
    private fun writeScrollbarConfig(writer: ProtocolWriter, value: ScrollbarConfig) {
        writer.writeF32(value.thickness)
        writer.writeF32(value.minThumb)
        writer.writeF32(value.thumbHitPadding)
        writer.writeI32(value.mode.value)
        writer.writeBoolU8(value.thumbDraggable)
        writer.writeI32(value.trackTapMode.value)
        writer.writeU16(value.fadeDelayMs)
        writer.writeU16(value.fadeDurationMs)
    }
    fun decodeIntRange(bytes: ByteArray): IntRange = readIntRange(ProtocolReader(bytes))
    private fun readIntRange(reader: ProtocolReader): IntRange {
        val start = reader.readI32()
        val end = reader.readI32()
        return IntRange(start, end)
    }
    fun encodeIntRange(value: IntRange): ByteArray {
        val writer = ProtocolWriter()
        writeIntRange(writer, value)
        return writer.toByteArray()
    }
    private fun writeIntRange(writer: ProtocolWriter, value: IntRange) {
        writer.writeI32(value.start)
        writer.writeI32(value.end)
    }
    fun decodePointF(bytes: ByteArray): PointF = readPointF(ProtocolReader(bytes))
    private fun readPointF(reader: ProtocolReader): PointF {
        val x = reader.readF32()
        val y = reader.readF32()
        return PointF(x, y)
    }
    fun encodePointF(value: PointF): ByteArray {
        val writer = ProtocolWriter()
        writePointF(writer, value)
        return writer.toByteArray()
    }
    private fun writePointF(writer: ProtocolWriter, value: PointF) {
        writer.writeF32(value.x)
        writer.writeF32(value.y)
    }
    fun decodeRect(bytes: ByteArray): Rect = readRect(ProtocolReader(bytes))
    private fun readRect(reader: ProtocolReader): Rect {
        val origin = readPointF(reader)
        val width = reader.readF32()
        val height = reader.readF32()
        return Rect(origin, width, height)
    }
    fun encodeRect(value: Rect): ByteArray {
        val writer = ProtocolWriter()
        writeRect(writer, value)
        return writer.toByteArray()
    }
    private fun writeRect(writer: ProtocolWriter, value: Rect) {
        writePointF(writer, value.origin)
        writer.writeF32(value.width)
        writer.writeF32(value.height)
    }
    fun decodeSize(bytes: ByteArray): Size = readSize(ProtocolReader(bytes))
    private fun readSize(reader: ProtocolReader): Size {
        val width = reader.readF32()
        val height = reader.readF32()
        return Size(width, height)
    }
    fun encodeSize(value: Size): ByteArray {
        val writer = ProtocolWriter()
        writeSize(writer, value)
        return writer.toByteArray()
    }
    private fun writeSize(writer: ProtocolWriter, value: Size) {
        writer.writeF32(value.width)
        writer.writeF32(value.height)
    }
    private fun readTabStopGroup(reader: ProtocolReader): TabStopGroup {
        val index = reader.readU32()
        val ranges = readListTextRange(reader)
        val defaultText = reader.readUtf8String()
        return TabStopGroup(index, ranges, defaultText)
    }
    fun encodeTabStopGroup(value: TabStopGroup): ByteArray {
        val writer = ProtocolWriter()
        writeTabStopGroup(writer, value)
        return writer.toByteArray()
    }
    private fun writeTabStopGroup(writer: ProtocolWriter, value: TabStopGroup) {
        writer.writeU32(value.index)
        writeListTextRange(writer, value.ranges)
        writer.writeUtf8String(value.defaultText)
    }
    fun decodeTextChange(bytes: ByteArray): TextChange = readTextChange(ProtocolReader(bytes))
    private fun readTextChange(reader: ProtocolReader): TextChange {
        val range = readTextRange(reader)
        val newText = reader.readUtf8String()
        return TextChange(range, newText)
    }
    private fun writeTextChange(writer: ProtocolWriter, value: TextChange) {
        writeTextRange(writer, value.range)
        writer.writeUtf8String(value.newText)
    }
    fun decodeTextEdit(bytes: ByteArray): TextEdit = readTextEdit(ProtocolReader(bytes))
    private fun readTextEdit(reader: ProtocolReader): TextEdit {
        val range = readTextRange(reader)
        val newText = reader.readUtf8String()
        return TextEdit(range, newText)
    }
    fun encodeTextEdit(value: TextEdit): ByteArray {
        val writer = ProtocolWriter()
        writeTextEdit(writer, value)
        return writer.toByteArray()
    }
    private fun writeTextEdit(writer: ProtocolWriter, value: TextEdit) {
        writeTextRange(writer, value.range)
        writer.writeUtf8String(value.newText)
    }
    fun decodeTextPosition(bytes: ByteArray): TextPosition = readTextPosition(ProtocolReader(bytes))
    private fun readTextPosition(reader: ProtocolReader): TextPosition {
        val line = reader.readI32()
        val column = reader.readI32()
        return TextPosition(line, column)
    }
    fun encodeTextPosition(value: TextPosition): ByteArray {
        val writer = ProtocolWriter()
        writeTextPosition(writer, value)
        return writer.toByteArray()
    }
    private fun writeTextPosition(writer: ProtocolWriter, value: TextPosition) {
        writer.writeI32(value.line)
        writer.writeI32(value.column)
    }
    fun decodeTextRange(bytes: ByteArray): TextRange = readTextRange(ProtocolReader(bytes))
    private fun readTextRange(reader: ProtocolReader): TextRange {
        val start = readTextPosition(reader)
        val end = readTextPosition(reader)
        return TextRange(start, end)
    }
    fun encodeTextRange(value: TextRange): ByteArray {
        val writer = ProtocolWriter()
        writeTextRange(writer, value)
        return writer.toByteArray()
    }
    private fun writeTextRange(writer: ProtocolWriter, value: TextRange) {
        writeTextPosition(writer, value.start)
        writeTextPosition(writer, value.end)
    }
    private fun readImeCommand(reader: ProtocolReader): ImeCommand {
        val kind = ImeCommandKind.fromValue(reader.readI32())
        val targetRange = readImeOffsetRange(reader)
        val selectionAfter = readImeSelection(reader)
        val text = reader.readUtf8String()
        val deleteBefore = reader.readI64()
        val deleteAfter = reader.readI64()
        val textUnit = ImeTextUnit.fromValue(reader.readI32())
        return ImeCommand(kind, targetRange, selectionAfter, text, deleteBefore, deleteAfter, textUnit)
    }
    fun encodeImeCommand(value: ImeCommand): ByteArray {
        val writer = ProtocolWriter()
        writeImeCommand(writer, value)
        return writer.toByteArray()
    }
    private fun writeImeCommand(writer: ProtocolWriter, value: ImeCommand) {
        writer.writeI32(value.kind.value)
        writeImeOffsetRange(writer, value.targetRange)
        writeImeSelection(writer, value.selectionAfter)
        writer.writeUtf8String(value.text)
        writer.writeI64(value.deleteBefore)
        writer.writeI64(value.deleteAfter)
        writer.writeI32(value.textUnit.value)
    }
    private fun readImeCommandBatch(reader: ProtocolReader): ImeCommandBatch {
        val sessionId = reader.readU64()
        val commands = readListImeCommand(reader)
        return ImeCommandBatch(sessionId, commands)
    }
    fun encodeImeCommandBatch(value: ImeCommandBatch): ByteArray {
        val writer = ProtocolWriter()
        writeImeCommandBatch(writer, value)
        return writer.toByteArray()
    }
    private fun writeImeCommandBatch(writer: ProtocolWriter, value: ImeCommandBatch) {
        writer.writeU64(value.sessionId)
        writeListImeCommand(writer, value.commands)
    }
    fun decodeImeOffsetRange(bytes: ByteArray): ImeOffsetRange = readImeOffsetRange(ProtocolReader(bytes))
    private fun readImeOffsetRange(reader: ProtocolReader): ImeOffsetRange {
        val coordinateSpace = ImeCoordinateSpace.fromValue(reader.readI32())
        val startUtf16 = reader.readI64()
        val endUtf16 = reader.readI64()
        return ImeOffsetRange(coordinateSpace, startUtf16, endUtf16)
    }
    fun encodeImeOffsetRange(value: ImeOffsetRange): ByteArray {
        val writer = ProtocolWriter()
        writeImeOffsetRange(writer, value)
        return writer.toByteArray()
    }
    private fun writeImeOffsetRange(writer: ProtocolWriter, value: ImeOffsetRange) {
        writer.writeI32(value.coordinateSpace.value)
        writer.writeI64(value.startUtf16)
        writer.writeI64(value.endUtf16)
    }
    fun decodeImeSelection(bytes: ByteArray): ImeSelection = readImeSelection(ProtocolReader(bytes))
    private fun readImeSelection(reader: ProtocolReader): ImeSelection {
        val coordinateSpace = ImeCoordinateSpace.fromValue(reader.readI32())
        val anchorUtf16 = reader.readI64()
        val activeUtf16 = reader.readI64()
        val affinity = CaretAffinity.fromValue(reader.readI32())
        return ImeSelection(coordinateSpace, anchorUtf16, activeUtf16, affinity)
    }
    fun encodeImeSelection(value: ImeSelection): ByteArray {
        val writer = ProtocolWriter()
        writeImeSelection(writer, value)
        return writer.toByteArray()
    }
    private fun writeImeSelection(writer: ProtocolWriter, value: ImeSelection) {
        writer.writeI32(value.coordinateSpace.value)
        writer.writeI64(value.anchorUtf16)
        writer.writeI64(value.activeUtf16)
        writer.writeI32(value.affinity.value)
    }
    fun decodeImeState(bytes: ByteArray): ImeState = readImeState(ProtocolReader(bytes))
    private fun readImeState(reader: ProtocolReader): ImeState {
        val resultCode = ImeResultCode.fromValue(reader.readI32())
        val sessionId = reader.readU64()
        val stateRevision = reader.readU64()
        val selection = readImeSelection(reader)
        val compositionRange = readImeOffsetRange(reader)
        return ImeState(resultCode, sessionId, stateRevision, selection, compositionRange)
    }
    private fun writeImeState(writer: ProtocolWriter, value: ImeState) {
        writer.writeI32(value.resultCode.value)
        writer.writeU64(value.sessionId)
        writer.writeU64(value.stateRevision)
        writeImeSelection(writer, value.selection)
        writeImeOffsetRange(writer, value.compositionRange)
    }
    fun decodeImeTextContext(bytes: ByteArray): ImeTextContext = readImeTextContext(ProtocolReader(bytes))
    private fun readImeTextContext(reader: ProtocolReader): ImeTextContext {
        val resultCode = ImeResultCode.fromValue(reader.readI32())
        val sliceStartUtf16 = reader.readI64()
        val totalLengthUtf16 = reader.readI64()
        val text = reader.readUtf8String()
        val selection = readImeSelection(reader)
        val compositionRange = readImeOffsetRange(reader)
        return ImeTextContext(resultCode, sliceStartUtf16, totalLengthUtf16, text, selection, compositionRange)
    }
    private fun writeImeTextContext(writer: ProtocolWriter, value: ImeTextContext) {
        writer.writeI32(value.resultCode.value)
        writer.writeI64(value.sliceStartUtf16)
        writer.writeI64(value.totalLengthUtf16)
        writer.writeUtf8String(value.text)
        writeImeSelection(writer, value.selection)
        writeImeOffsetRange(writer, value.compositionRange)
    }
    private fun readImeTextUpdateBatch(reader: ProtocolReader): ImeTextUpdateBatch {
        val sessionId = reader.readU64()
        val expectedStateRevision = reader.readU64()
        val steps = readListImeTextUpdateStep(reader)
        return ImeTextUpdateBatch(sessionId, expectedStateRevision, steps)
    }
    fun encodeImeTextUpdateBatch(value: ImeTextUpdateBatch): ByteArray {
        val writer = ProtocolWriter()
        writeImeTextUpdateBatch(writer, value)
        return writer.toByteArray()
    }
    private fun writeImeTextUpdateBatch(writer: ProtocolWriter, value: ImeTextUpdateBatch) {
        writer.writeU64(value.sessionId)
        writer.writeU64(value.expectedStateRevision)
        writeListImeTextUpdateStep(writer, value.steps)
    }
    private fun readImeTextUpdateStep(reader: ProtocolReader): ImeTextUpdateStep {
        val oldText = reader.readUtf8String()
        val patchRange = readImeOffsetRange(reader)
        val replacementText = reader.readUtf8String()
        val selectionAfter = readImeSelection(reader)
        val compositionAfter = readImeOffsetRange(reader)
        return ImeTextUpdateStep(oldText, patchRange, replacementText, selectionAfter, compositionAfter)
    }
    fun encodeImeTextUpdateStep(value: ImeTextUpdateStep): ByteArray {
        val writer = ProtocolWriter()
        writeImeTextUpdateStep(writer, value)
        return writer.toByteArray()
    }
    private fun writeImeTextUpdateStep(writer: ProtocolWriter, value: ImeTextUpdateStep) {
        writer.writeUtf8String(value.oldText)
        writeImeOffsetRange(writer, value.patchRange)
        writer.writeUtf8String(value.replacementText)
        writeImeSelection(writer, value.selectionAfter)
        writeImeOffsetRange(writer, value.compositionAfter)
    }
    private fun readGestureEvent(reader: ProtocolReader): GestureEvent {
        val `type` = EventType.fromValue(reader.readI32())
        val points = readListPointF(reader)
        val modifiers = reader.readI32()
        val wheelDeltaX = reader.readF32()
        val wheelDeltaY = reader.readF32()
        val directScale = reader.readF32()
        return GestureEvent(`type`, points, modifiers, wheelDeltaX, wheelDeltaY, directScale)
    }
    fun encodeGestureEvent(value: GestureEvent): ByteArray {
        val writer = ProtocolWriter()
        writeGestureEvent(writer, value)
        return writer.toByteArray()
    }
    private fun writeGestureEvent(writer: ProtocolWriter, value: GestureEvent) {
        writer.writeI32(value.`type`.value)
        writeListPointF(writer, value.points)
        writer.writeI32(value.modifiers)
        writer.writeF32(value.wheelDeltaX)
        writer.writeF32(value.wheelDeltaY)
        writer.writeF32(value.directScale)
    }
    fun decodeHitTarget(bytes: ByteArray): HitTarget = readHitTarget(ProtocolReader(bytes))
    private fun readHitTarget(reader: ProtocolReader): HitTarget {
        val `type` = HitTargetType.fromValue(reader.readI32())
        val line = reader.readI32()
        val column = reader.readI32()
        val iconId = reader.readI32()
        val colorValue = reader.readI32()
        return HitTarget(`type`, line, column, iconId, colorValue)
    }
    private fun writeHitTarget(writer: ProtocolWriter, value: HitTarget) {
        writer.writeI32(value.`type`.value)
        writer.writeI32(value.line)
        writer.writeI32(value.column)
        writer.writeI32(value.iconId)
        writer.writeI32(value.colorValue)
    }
    fun decodeKeyBinding(bytes: ByteArray): KeyBinding = readKeyBinding(ProtocolReader(bytes))
    private fun readKeyBinding(reader: ProtocolReader): KeyBinding {
        val first = readKeyChord(reader)
        val second = readKeyChord(reader)
        val command = reader.readU32()
        return KeyBinding(first, second, command)
    }
    fun encodeKeyBinding(value: KeyBinding): ByteArray {
        val writer = ProtocolWriter()
        writeKeyBinding(writer, value)
        return writer.toByteArray()
    }
    private fun writeKeyBinding(writer: ProtocolWriter, value: KeyBinding) {
        writeKeyChord(writer, value.first)
        writeKeyChord(writer, value.second)
        writer.writeU32(value.command)
    }
    fun decodeKeyChord(bytes: ByteArray): KeyChord = readKeyChord(ProtocolReader(bytes))
    private fun readKeyChord(reader: ProtocolReader): KeyChord {
        val modifiers = reader.readU8()
        val keyCode = reader.readU16()
        return KeyChord(modifiers, keyCode)
    }
    fun encodeKeyChord(value: KeyChord): ByteArray {
        val writer = ProtocolWriter()
        writeKeyChord(writer, value)
        return writer.toByteArray()
    }
    private fun writeKeyChord(writer: ProtocolWriter, value: KeyChord) {
        writer.writeU8(value.modifiers)
        writer.writeU16(value.keyCode)
    }
    fun decodeSearchOptions(bytes: ByteArray): SearchOptions = readSearchOptions(ProtocolReader(bytes))
    private fun readSearchOptions(reader: ProtocolReader): SearchOptions {
        val caseSensitive = reader.readBoolI32()
        val wholeWord = reader.readBoolI32()
        val useRegex = reader.readBoolI32()
        val wrapAround = reader.readBoolI32()
        val maxMatches = reader.readU32()
        return SearchOptions(caseSensitive, wholeWord, useRegex, wrapAround, maxMatches)
    }
    fun encodeSearchOptions(value: SearchOptions): ByteArray {
        val writer = ProtocolWriter()
        writeSearchOptions(writer, value)
        return writer.toByteArray()
    }
    private fun writeSearchOptions(writer: ProtocolWriter, value: SearchOptions) {
        writer.writeBoolI32(value.caseSensitive)
        writer.writeBoolI32(value.wholeWord)
        writer.writeBoolI32(value.useRegex)
        writer.writeBoolI32(value.wrapAround)
        writer.writeU32(value.maxMatches)
    }
    private fun readSearchRequest(reader: ProtocolReader): SearchRequest {
        val pattern = reader.readUtf8String()
        val options = readSearchOptions(reader)
        return SearchRequest(pattern, options)
    }
    fun encodeSearchRequest(value: SearchRequest): ByteArray {
        val writer = ProtocolWriter()
        writeSearchRequest(writer, value)
        return writer.toByteArray()
    }
    private fun writeSearchRequest(writer: ProtocolWriter, value: SearchRequest) {
        writer.writeUtf8String(value.pattern)
        writeSearchOptions(writer, value.options)
    }
    fun decodeSearchState(bytes: ByteArray): SearchState = readSearchState(ProtocolReader(bytes))
    private fun readSearchState(reader: ProtocolReader): SearchState {
        val status = SearchStatus.fromValue(reader.readI32())
        val pattern = reader.readUtf8String()
        val options = readSearchOptions(reader)
        val generation = reader.readU64()
        val matchCount = reader.readU32()
        val currentIndex = reader.readI32()
        val hasCurrentMatch = reader.readBoolI32()
        val currentRange = readTextRange(reader)
        val errorMessage = reader.readUtf8String()
        return SearchState(status, pattern, options, generation, matchCount, currentIndex, hasCurrentMatch, currentRange, errorMessage)
    }
    private fun writeSearchState(writer: ProtocolWriter, value: SearchState) {
        writer.writeI32(value.status.value)
        writer.writeUtf8String(value.pattern)
        writeSearchOptions(writer, value.options)
        writer.writeU64(value.generation)
        writer.writeU32(value.matchCount)
        writer.writeI32(value.currentIndex)
        writer.writeBoolI32(value.hasCurrentMatch)
        writeTextRange(writer, value.currentRange)
        writer.writeUtf8String(value.errorMessage)
    }
    fun decodeCursor(bytes: ByteArray): Cursor = readCursor(ProtocolReader(bytes))
    private fun readCursor(reader: ProtocolReader): Cursor {
        val textPosition = readTextPosition(reader)
        val position = readPointF(reader)
        val height = reader.readF32()
        val visible = reader.readBoolI32()
        val showDragger = reader.readBoolI32()
        return Cursor(textPosition, position, height, visible, showDragger)
    }
    private fun writeCursor(writer: ProtocolWriter, value: Cursor) {
        writeTextPosition(writer, value.textPosition)
        writePointF(writer, value.position)
        writer.writeF32(value.height)
        writer.writeBoolI32(value.visible)
        writer.writeBoolI32(value.showDragger)
    }
    fun decodeCursorRect(bytes: ByteArray): CursorRect = readCursorRect(ProtocolReader(bytes))
    private fun readCursorRect(reader: ProtocolReader): CursorRect {
        val x = reader.readF32()
        val y = reader.readF32()
        val height = reader.readF32()
        return CursorRect(x, y, height)
    }
    fun encodeCursorRect(value: CursorRect): ByteArray {
        val writer = ProtocolWriter()
        writeCursorRect(writer, value)
        return writer.toByteArray()
    }
    private fun writeCursorRect(writer: ProtocolWriter, value: CursorRect) {
        writer.writeF32(value.x)
        writer.writeF32(value.y)
        writer.writeF32(value.height)
    }
    fun decodeEditorRenderModel(bytes: ByteArray): EditorRenderModel = readEditorRenderModel(ProtocolReader(bytes))
    private fun readEditorRenderModel(reader: ProtocolReader): EditorRenderModel {
        val splitX = reader.readF32()
        val splitLineVisible = reader.readBoolI32()
        val scrollX = reader.readF32()
        val scrollY = reader.readF32()
        val viewportSize = readSize(reader)
        val currentLine = readPointF(reader)
        val currentLineRenderMode = CurrentLineRenderMode.fromValue(reader.readI32())
        val lines = readListVisualLine(reader)
        val cursor = readCursor(reader)
        val rangeEffects = readListRangeEffectRenderItem(reader)
        val selectionStartHandle = readSelectionHandle(reader)
        val selectionEndHandle = readSelectionHandle(reader)
        val guideSegments = readListGuideSegment(reader)
        val maxGutterIcons = reader.readU32()
        val gutterIcons = readListGutterIconRenderItem(reader)
        val foldMarkers = readListFoldMarkerRenderItem(reader)
        val verticalScrollbar = readScrollbarModel(reader)
        val horizontalScrollbar = readScrollbarModel(reader)
        val gutterSticky = reader.readBoolI32()
        val gutterVisible = reader.readBoolI32()
        val pointerCursorType = PointerCursorType.fromValue(reader.readI32())
        return EditorRenderModel(splitX, splitLineVisible, scrollX, scrollY, viewportSize, currentLine, currentLineRenderMode, lines, cursor, rangeEffects, selectionStartHandle, selectionEndHandle, guideSegments, maxGutterIcons, gutterIcons, foldMarkers, verticalScrollbar, horizontalScrollbar, gutterSticky, gutterVisible, pointerCursorType)
    }
    private fun writeEditorRenderModel(writer: ProtocolWriter, value: EditorRenderModel) {
        writer.writeF32(value.splitX)
        writer.writeBoolI32(value.splitLineVisible)
        writer.writeF32(value.scrollX)
        writer.writeF32(value.scrollY)
        writeSize(writer, value.viewportSize)
        writePointF(writer, value.currentLine)
        writer.writeI32(value.currentLineRenderMode.value)
        writeListVisualLine(writer, value.lines)
        writeCursor(writer, value.cursor)
        writeListRangeEffectRenderItem(writer, value.rangeEffects)
        writeSelectionHandle(writer, value.selectionStartHandle)
        writeSelectionHandle(writer, value.selectionEndHandle)
        writeListGuideSegment(writer, value.guideSegments)
        writer.writeU32(value.maxGutterIcons)
        writeListGutterIconRenderItem(writer, value.gutterIcons)
        writeListFoldMarkerRenderItem(writer, value.foldMarkers)
        writeScrollbarModel(writer, value.verticalScrollbar)
        writeScrollbarModel(writer, value.horizontalScrollbar)
        writer.writeBoolI32(value.gutterSticky)
        writer.writeBoolI32(value.gutterVisible)
        writer.writeI32(value.pointerCursorType.value)
    }
    fun decodeFoldMarkerRenderItem(bytes: ByteArray): FoldMarkerRenderItem = readFoldMarkerRenderItem(ProtocolReader(bytes))
    private fun readFoldMarkerRenderItem(reader: ProtocolReader): FoldMarkerRenderItem {
        val logicalLine = reader.readI32()
        val foldState = FoldState.fromValue(reader.readI32())
        val rect = readRect(reader)
        return FoldMarkerRenderItem(logicalLine, foldState, rect)
    }
    private fun writeFoldMarkerRenderItem(writer: ProtocolWriter, value: FoldMarkerRenderItem) {
        writer.writeI32(value.logicalLine)
        writer.writeI32(value.foldState.value)
        writeRect(writer, value.rect)
    }
    fun decodeGuideSegment(bytes: ByteArray): GuideSegment = readGuideSegment(ProtocolReader(bytes))
    private fun readGuideSegment(reader: ProtocolReader): GuideSegment {
        val direction = GuideDirection.fromValue(reader.readI32())
        val `type` = GuideType.fromValue(reader.readI32())
        val style = GuideStyle.fromValue(reader.readI32())
        val start = readPointF(reader)
        val end = readPointF(reader)
        val arrowEnd = reader.readBoolI32()
        return GuideSegment(direction, `type`, style, start, end, arrowEnd)
    }
    private fun writeGuideSegment(writer: ProtocolWriter, value: GuideSegment) {
        writer.writeI32(value.direction.value)
        writer.writeI32(value.`type`.value)
        writer.writeI32(value.style.value)
        writePointF(writer, value.start)
        writePointF(writer, value.end)
        writer.writeBoolI32(value.arrowEnd)
    }
    fun decodeGutterIconRenderItem(bytes: ByteArray): GutterIconRenderItem = readGutterIconRenderItem(ProtocolReader(bytes))
    private fun readGutterIconRenderItem(reader: ProtocolReader): GutterIconRenderItem {
        val logicalLine = reader.readI32()
        val iconId = reader.readI32()
        val rect = readRect(reader)
        return GutterIconRenderItem(logicalLine, iconId, rect)
    }
    private fun writeGutterIconRenderItem(writer: ProtocolWriter, value: GutterIconRenderItem) {
        writer.writeI32(value.logicalLine)
        writer.writeI32(value.iconId)
        writeRect(writer, value.rect)
    }
    fun decodeLayoutMetrics(bytes: ByteArray): LayoutMetrics = readLayoutMetrics(ProtocolReader(bytes))
    private fun readLayoutMetrics(reader: ProtocolReader): LayoutMetrics {
        val fontHeight = reader.readF32()
        val fontAscent = reader.readF32()
        val lineSpacingAdd = reader.readF32()
        val lineSpacingMult = reader.readF32()
        val lineNumberMargin = reader.readF32()
        val lineNumberWidth = reader.readF32()
        val contentStartPadding = reader.readF32()
        val maxGutterIcons = reader.readU32()
        val inlayHintPadding = reader.readF32()
        val inlayHintMargin = reader.readF32()
        val foldArrowMode = FoldArrowMode.fromValue(reader.readI32())
        val hasFoldRegions = reader.readBoolI32()
        val gutterSticky = reader.readBoolI32()
        val gutterVisible = reader.readBoolI32()
        return LayoutMetrics(fontHeight, fontAscent, lineSpacingAdd, lineSpacingMult, lineNumberMargin, lineNumberWidth, contentStartPadding, maxGutterIcons, inlayHintPadding, inlayHintMargin, foldArrowMode, hasFoldRegions, gutterSticky, gutterVisible)
    }
    private fun writeLayoutMetrics(writer: ProtocolWriter, value: LayoutMetrics) {
        writer.writeF32(value.fontHeight)
        writer.writeF32(value.fontAscent)
        writer.writeF32(value.lineSpacingAdd)
        writer.writeF32(value.lineSpacingMult)
        writer.writeF32(value.lineNumberMargin)
        writer.writeF32(value.lineNumberWidth)
        writer.writeF32(value.contentStartPadding)
        writer.writeU32(value.maxGutterIcons)
        writer.writeF32(value.inlayHintPadding)
        writer.writeF32(value.inlayHintMargin)
        writer.writeI32(value.foldArrowMode.value)
        writer.writeBoolI32(value.hasFoldRegions)
        writer.writeBoolI32(value.gutterSticky)
        writer.writeBoolI32(value.gutterVisible)
    }
    fun decodeRangeEffectRenderItem(bytes: ByteArray): RangeEffectRenderItem = readRangeEffectRenderItem(ProtocolReader(bytes))
    private fun readRangeEffectRenderItem(reader: ProtocolReader): RangeEffectRenderItem {
        val rect = readRect(reader)
        val kind = RangeEffectKind.fromValue(reader.readI32())
        val style = readRangeEffectStyle(reader)
        return RangeEffectRenderItem(rect, kind, style)
    }
    private fun writeRangeEffectRenderItem(writer: ProtocolWriter, value: RangeEffectRenderItem) {
        writeRect(writer, value.rect)
        writer.writeI32(value.kind.value)
        writeRangeEffectStyle(writer, value.style)
    }
    fun decodeScrollMetrics(bytes: ByteArray): ScrollMetrics = readScrollMetrics(ProtocolReader(bytes))
    private fun readScrollMetrics(reader: ProtocolReader): ScrollMetrics {
        val scale = reader.readF32()
        val scrollX = reader.readF32()
        val scrollY = reader.readF32()
        val maxScrollX = reader.readF32()
        val maxScrollY = reader.readF32()
        val contentSize = readSize(reader)
        val viewportSize = readSize(reader)
        val textAreaX = reader.readF32()
        val textAreaWidth = reader.readF32()
        val canScrollX = reader.readBoolI32()
        val canScrollY = reader.readBoolI32()
        return ScrollMetrics(scale, scrollX, scrollY, maxScrollX, maxScrollY, contentSize, viewportSize, textAreaX, textAreaWidth, canScrollX, canScrollY)
    }
    private fun writeScrollMetrics(writer: ProtocolWriter, value: ScrollMetrics) {
        writer.writeF32(value.scale)
        writer.writeF32(value.scrollX)
        writer.writeF32(value.scrollY)
        writer.writeF32(value.maxScrollX)
        writer.writeF32(value.maxScrollY)
        writeSize(writer, value.contentSize)
        writeSize(writer, value.viewportSize)
        writer.writeF32(value.textAreaX)
        writer.writeF32(value.textAreaWidth)
        writer.writeBoolI32(value.canScrollX)
        writer.writeBoolI32(value.canScrollY)
    }
    fun decodeScrollbarModel(bytes: ByteArray): ScrollbarModel = readScrollbarModel(ProtocolReader(bytes))
    private fun readScrollbarModel(reader: ProtocolReader): ScrollbarModel {
        val visible = reader.readBoolI32()
        val alpha = reader.readF32()
        val thumbActive = reader.readBoolI32()
        val track = readRect(reader)
        val thumb = readRect(reader)
        return ScrollbarModel(visible, alpha, thumbActive, track, thumb)
    }
    private fun writeScrollbarModel(writer: ProtocolWriter, value: ScrollbarModel) {
        writer.writeBoolI32(value.visible)
        writer.writeF32(value.alpha)
        writer.writeBoolI32(value.thumbActive)
        writeRect(writer, value.track)
        writeRect(writer, value.thumb)
    }
    fun decodeSelectionHandle(bytes: ByteArray): SelectionHandle = readSelectionHandle(ProtocolReader(bytes))
    private fun readSelectionHandle(reader: ProtocolReader): SelectionHandle {
        val position = readPointF(reader)
        val height = reader.readF32()
        val visible = reader.readBoolI32()
        return SelectionHandle(position, height, visible)
    }
    private fun writeSelectionHandle(writer: ProtocolWriter, value: SelectionHandle) {
        writePointF(writer, value.position)
        writer.writeF32(value.height)
        writer.writeBoolI32(value.visible)
    }
    fun decodeVisualLine(bytes: ByteArray): VisualLine = readVisualLine(ProtocolReader(bytes))
    private fun readVisualLine(reader: ProtocolReader): VisualLine {
        val logicalLine = reader.readI32()
        val wrapIndex = reader.readI32()
        val lineNumberPosition = readPointF(reader)
        val runs = readListVisualRun(reader)
        val kind = VisualLineKind.fromValue(reader.readI32())
        val ownsGutterSemantics = reader.readBoolI32()
        val foldState = FoldState.fromValue(reader.readI32())
        val lineNumber = reader.readI32()
        val lineBackgroundColor = reader.readI32()
        val gutterBackgroundColor = reader.readI32()
        return VisualLine(logicalLine, wrapIndex, lineNumberPosition, runs, kind, ownsGutterSemantics, foldState, lineNumber, lineBackgroundColor, gutterBackgroundColor)
    }
    private fun writeVisualLine(writer: ProtocolWriter, value: VisualLine) {
        writer.writeI32(value.logicalLine)
        writer.writeI32(value.wrapIndex)
        writePointF(writer, value.lineNumberPosition)
        writeListVisualRun(writer, value.runs)
        writer.writeI32(value.kind.value)
        writer.writeBoolI32(value.ownsGutterSemantics)
        writer.writeI32(value.foldState.value)
        writer.writeI32(value.lineNumber)
        writer.writeI32(value.lineBackgroundColor)
        writer.writeI32(value.gutterBackgroundColor)
    }
    fun decodeVisualRun(bytes: ByteArray): VisualRun = readVisualRun(ProtocolReader(bytes))
    private fun readVisualRun(reader: ProtocolReader): VisualRun {
        val `type` = VisualRunType.fromValue(reader.readI32())
        val x = reader.readF32()
        val y = reader.readF32()
        val text = reader.readUtf8String()
        val style = readTextStyle(reader)
        val iconId = reader.readI32()
        val colorValue = reader.readI32()
        val width = reader.readF32()
        val padding = reader.readF32()
        val margin = reader.readF32()
        val active = reader.readBoolI32()
        return VisualRun(`type`, x, y, text, style, iconId, colorValue, width, padding, margin, active)
    }
    private fun writeVisualRun(writer: ProtocolWriter, value: VisualRun) {
        writer.writeI32(value.`type`.value)
        writer.writeF32(value.x)
        writer.writeF32(value.y)
        writer.writeUtf8String(value.text)
        writeTextStyle(writer, value.style)
        writer.writeI32(value.iconId)
        writer.writeI32(value.colorValue)
        writer.writeF32(value.width)
        writer.writeF32(value.padding)
        writer.writeF32(value.margin)
        writer.writeBoolI32(value.active)
    }
    private fun readListBracketGuide(reader: ProtocolReader): List<BracketGuide> {
        val count = reader.readListCount()
        return List(count) {
            readBracketGuide(reader)
        }
    }
    private fun writeListBracketGuide(writer: ProtocolWriter, values: List<BracketGuide>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeBracketGuide(writer, item)
        }
    }
    private fun readListCodeLensItem(reader: ProtocolReader): List<CodeLensItem> {
        val count = reader.readListCount()
        return List(count) {
            readCodeLensItem(reader)
        }
    }
    private fun writeListCodeLensItem(writer: ProtocolWriter, values: List<CodeLensItem>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeCodeLensItem(writer, item)
        }
    }
    private fun readListDiagnostic(reader: ProtocolReader): List<Diagnostic> {
        val count = reader.readListCount()
        return List(count) {
            readDiagnostic(reader)
        }
    }
    private fun writeListDiagnostic(writer: ProtocolWriter, values: List<Diagnostic>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeDiagnostic(writer, item)
        }
    }
    private fun readListDiffChange(reader: ProtocolReader): List<DiffChange> {
        val count = reader.readListCount()
        return List(count) {
            readDiffChange(reader)
        }
    }
    private fun writeListDiffChange(writer: ProtocolWriter, values: List<DiffChange>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeDiffChange(writer, item)
        }
    }
    private fun readListDocumentHighlight(reader: ProtocolReader): List<DocumentHighlight> {
        val count = reader.readListCount()
        return List(count) {
            readDocumentHighlight(reader)
        }
    }
    private fun writeListDocumentHighlight(writer: ProtocolWriter, values: List<DocumentHighlight>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeDocumentHighlight(writer, item)
        }
    }
    private fun readListFlowGuide(reader: ProtocolReader): List<FlowGuide> {
        val count = reader.readListCount()
        return List(count) {
            readFlowGuide(reader)
        }
    }
    private fun writeListFlowGuide(writer: ProtocolWriter, values: List<FlowGuide>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeFlowGuide(writer, item)
        }
    }
    private fun readListFoldMarkerRenderItem(reader: ProtocolReader): List<FoldMarkerRenderItem> {
        val count = reader.readListCount()
        return List(count) {
            readFoldMarkerRenderItem(reader)
        }
    }
    private fun writeListFoldMarkerRenderItem(writer: ProtocolWriter, values: List<FoldMarkerRenderItem>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeFoldMarkerRenderItem(writer, item)
        }
    }
    private fun readListFoldRegion(reader: ProtocolReader): List<FoldRegion> {
        val count = reader.readListCount()
        return List(count) {
            readFoldRegion(reader)
        }
    }
    private fun writeListFoldRegion(writer: ProtocolWriter, values: List<FoldRegion>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeFoldRegion(writer, item)
        }
    }
    private fun readListGuideSegment(reader: ProtocolReader): List<GuideSegment> {
        val count = reader.readListCount()
        return List(count) {
            readGuideSegment(reader)
        }
    }
    private fun writeListGuideSegment(writer: ProtocolWriter, values: List<GuideSegment>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeGuideSegment(writer, item)
        }
    }
    private fun readListGutterIcon(reader: ProtocolReader): List<GutterIcon> {
        val count = reader.readListCount()
        return List(count) {
            readGutterIcon(reader)
        }
    }
    private fun writeListGutterIcon(writer: ProtocolWriter, values: List<GutterIcon>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeGutterIcon(writer, item)
        }
    }
    private fun readListGutterIconRenderItem(reader: ProtocolReader): List<GutterIconRenderItem> {
        val count = reader.readListCount()
        return List(count) {
            readGutterIconRenderItem(reader)
        }
    }
    private fun writeListGutterIconRenderItem(writer: ProtocolWriter, values: List<GutterIconRenderItem>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeGutterIconRenderItem(writer, item)
        }
    }
    private fun readListImeCommand(reader: ProtocolReader): List<ImeCommand> {
        val count = reader.readListCount()
        return List(count) {
            readImeCommand(reader)
        }
    }
    private fun writeListImeCommand(writer: ProtocolWriter, values: List<ImeCommand>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeImeCommand(writer, item)
        }
    }
    private fun readListImeTextUpdateStep(reader: ProtocolReader): List<ImeTextUpdateStep> {
        val count = reader.readListCount()
        return List(count) {
            readImeTextUpdateStep(reader)
        }
    }
    private fun writeListImeTextUpdateStep(writer: ProtocolWriter, values: List<ImeTextUpdateStep>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeImeTextUpdateStep(writer, item)
        }
    }
    private fun readListIndentGuide(reader: ProtocolReader): List<IndentGuide> {
        val count = reader.readListCount()
        return List(count) {
            readIndentGuide(reader)
        }
    }
    private fun writeListIndentGuide(writer: ProtocolWriter, values: List<IndentGuide>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeIndentGuide(writer, item)
        }
    }
    private fun readListInlayHint(reader: ProtocolReader): List<InlayHint> {
        val count = reader.readListCount()
        return List(count) {
            readInlayHint(reader)
        }
    }
    private fun writeListInlayHint(writer: ProtocolWriter, values: List<InlayHint>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeInlayHint(writer, item)
        }
    }
    private fun readListKeyBinding(reader: ProtocolReader): List<KeyBinding> {
        val count = reader.readListCount()
        return List(count) {
            readKeyBinding(reader)
        }
    }
    private fun writeListKeyBinding(writer: ProtocolWriter, values: List<KeyBinding>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeKeyBinding(writer, item)
        }
    }
    private fun readListLinkSpan(reader: ProtocolReader): List<LinkSpan> {
        val count = reader.readListCount()
        return List(count) {
            readLinkSpan(reader)
        }
    }
    private fun writeListLinkSpan(writer: ProtocolWriter, values: List<LinkSpan>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeLinkSpan(writer, item)
        }
    }
    private fun readListPhantomText(reader: ProtocolReader): List<PhantomText> {
        val count = reader.readListCount()
        return List(count) {
            readPhantomText(reader)
        }
    }
    private fun writeListPhantomText(writer: ProtocolWriter, values: List<PhantomText>) {
        writer.writeI32(values.size)
        for (item in values) {
            writePhantomText(writer, item)
        }
    }
    private fun readListPointF(reader: ProtocolReader): List<PointF> {
        val count = reader.readListCount()
        return List(count) {
            readPointF(reader)
        }
    }
    private fun writeListPointF(writer: ProtocolWriter, values: List<PointF>) {
        writer.writeI32(values.size)
        for (item in values) {
            writePointF(writer, item)
        }
    }
    private fun readListRangeEffectRenderItem(reader: ProtocolReader): List<RangeEffectRenderItem> {
        val count = reader.readListCount()
        return List(count) {
            readRangeEffectRenderItem(reader)
        }
    }
    private fun writeListRangeEffectRenderItem(writer: ProtocolWriter, values: List<RangeEffectRenderItem>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeRangeEffectRenderItem(writer, item)
        }
    }
    private fun readListSeparatorGuide(reader: ProtocolReader): List<SeparatorGuide> {
        val count = reader.readListCount()
        return List(count) {
            readSeparatorGuide(reader)
        }
    }
    private fun writeListSeparatorGuide(writer: ProtocolWriter, values: List<SeparatorGuide>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeSeparatorGuide(writer, item)
        }
    }
    private fun readListStyleSpan(reader: ProtocolReader): List<StyleSpan> {
        val count = reader.readListCount()
        return List(count) {
            readStyleSpan(reader)
        }
    }
    private fun writeListStyleSpan(writer: ProtocolWriter, values: List<StyleSpan>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeStyleSpan(writer, item)
        }
    }
    private fun readListTabStopGroup(reader: ProtocolReader): List<TabStopGroup> {
        val count = reader.readListCount()
        return List(count) {
            readTabStopGroup(reader)
        }
    }
    private fun writeListTabStopGroup(writer: ProtocolWriter, values: List<TabStopGroup>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeTabStopGroup(writer, item)
        }
    }
    private fun readListTextChange(reader: ProtocolReader): List<TextChange> {
        val count = reader.readListCount()
        return List(count) {
            readTextChange(reader)
        }
    }
    private fun writeListTextChange(writer: ProtocolWriter, values: List<TextChange>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeTextChange(writer, item)
        }
    }
    private fun readListTextEdit(reader: ProtocolReader): List<TextEdit> {
        val count = reader.readListCount()
        return List(count) {
            readTextEdit(reader)
        }
    }
    private fun writeListTextEdit(writer: ProtocolWriter, values: List<TextEdit>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeTextEdit(writer, item)
        }
    }
    private fun readListTextPosition(reader: ProtocolReader): List<TextPosition> {
        val count = reader.readListCount()
        return List(count) {
            readTextPosition(reader)
        }
    }
    private fun writeListTextPosition(writer: ProtocolWriter, values: List<TextPosition>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeTextPosition(writer, item)
        }
    }
    private fun readListTextRange(reader: ProtocolReader): List<TextRange> {
        val count = reader.readListCount()
        return List(count) {
            readTextRange(reader)
        }
    }
    private fun writeListTextRange(writer: ProtocolWriter, values: List<TextRange>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeTextRange(writer, item)
        }
    }
    private fun readListU8String(reader: ProtocolReader): List<String> {
        val count = reader.readListCount()
        return List(count) {
            reader.readUtf8String()
        }
    }
    private fun writeListU8String(writer: ProtocolWriter, values: List<String>) {
        writer.writeI32(values.size)
        for (item in values) {
            writer.writeUtf8String(item)
        }
    }
    private fun readListVisualLine(reader: ProtocolReader): List<VisualLine> {
        val count = reader.readListCount()
        return List(count) {
            readVisualLine(reader)
        }
    }
    private fun writeListVisualLine(writer: ProtocolWriter, values: List<VisualLine>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeVisualLine(writer, item)
        }
    }
    private fun readListVisualRun(reader: ProtocolReader): List<VisualRun> {
        val count = reader.readListCount()
        return List(count) {
            readVisualRun(reader)
        }
    }
    private fun writeListVisualRun(writer: ProtocolWriter, values: List<VisualRun>) {
        writer.writeI32(values.size)
        for (item in values) {
            writeVisualRun(writer, item)
        }
    }
}
