cmake_minimum_required(VERSION 3.10)
project(sweeteditor)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/bin)

if (PROJECT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
    set(SWEETEDITOR_DEFAULT_BUILD_TESTS ON)
    set(SWEETEDITOR_DEFAULT_BUILD_WASM_MODULES ON)
else ()
    set(SWEETEDITOR_DEFAULT_BUILD_TESTS OFF)
    set(SWEETEDITOR_DEFAULT_BUILD_WASM_MODULES OFF)
endif ()

option(SWEETEDITOR_BUILD_TESTS "Build SweetEditor tests" ${SWEETEDITOR_DEFAULT_BUILD_TESTS})
option(SWEETEDITOR_BUILD_SHARED "Build SweetEditor dynamic library" ON)
option(SWEETEDITOR_BUILD_STATIC "Build SweetEditor static library" ON)
option(SWEETEDITOR_BUILD_WASM_C_ABI "Build SweetEditor WebAssembly C ABI module" ${SWEETEDITOR_DEFAULT_BUILD_WASM_MODULES})
option(SWEETEDITOR_BUILD_WASM_EMBIND "Build SweetEditor WebAssembly embind module" ${SWEETEDITOR_DEFAULT_BUILD_WASM_MODULES})
option(SWEETEDITOR_BUILD_ANDROID_JNI "Build Android Java/JNI bridge" ON)
option(SWEETEDITOR_BUILD_APPLE_FRAMEWORK "Build SweetEditor Apple framework" OFF)
option(SWEETEDITOR_APPLE_STATIC_FRAMEWORK "Build Apple framework target with a static Mach-O binary" OFF)
set(SWEETEDITOR_SEARCH_IMPL "std" CACHE STRING "Search implementation: std, oniguruma")
set_property(CACHE SWEETEDITOR_SEARCH_IMPL PROPERTY STRINGS std oniguruma)

set(SWEETEDITOR_PROJECT_DIR ${PROJECT_SOURCE_DIR})
set(SWEETEDITOR_PUBLIC_INCLUDE_DIR ${SWEETEDITOR_PROJECT_DIR}/include)
set(SWEETEDITOR_PUBLIC_HEADER_DIR ${SWEETEDITOR_PUBLIC_INCLUDE_DIR}/sweeteditor)
set(SWEETEDITOR_STATIC_LIB_NAME "${PROJECT_NAME}_static")
set(SWEETEDITOR_SHARED_LIB_NAME "${PROJECT_NAME}")

include(cmake/SweetEditorTargets.cmake)
sweeteditor_configure_targets()

if (SWEETEDITOR_BUILD_TESTS)
    enable_testing()
    message(STATUS "Unit tests enabled")
    if (SWEETEDITOR_TARGETS_ENABLE_TESTS)
        add_subdirectory(${SWEETEDITOR_PROJECT_DIR}/tests)
    endif ()
endif ()

include(GNUInstallDirs)
set(INSTALL_TARGETS)
if (TARGET ${SWEETEDITOR_SHARED_LIB_NAME})
    list(APPEND INSTALL_TARGETS ${SWEETEDITOR_SHARED_LIB_NAME})
endif ()
if (TARGET ${SWEETEDITOR_STATIC_LIB_NAME})
    list(APPEND INSTALL_TARGETS ${SWEETEDITOR_STATIC_LIB_NAME})
endif ()
if (INSTALL_TARGETS)
    install(TARGETS ${INSTALL_TARGETS}
            RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
            LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
            ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
            FRAMEWORK DESTINATION ${CMAKE_INSTALL_LIBDIR}
    )
    foreach(TARGET_NAME ${INSTALL_TARGETS})
        sweeteditor_platform_install_target_debug_symbols(${TARGET_NAME})
    endforeach ()
endif ()

install(DIRECTORY ${SWEETEDITOR_PUBLIC_HEADER_DIR}
        DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
        FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp"
)
